sudo: required

language: generic

services:
  - docker

env:
  - DISPLAY=:99.0

before_install:
  - sudo apt update -qq > /dev/null
  - sudo apt install --yes --no-install-recommends xvfb

install:
  - make docker/build

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - make docker/run/test
